
from pylc.models.livegateapi.const import \
    MAX_ROUTER, MAX_ISP_ID, MIN_LAN_IF_INDEX, MAX_IF_INDEX, \
    MAX_NF_RULE, MAX_VLANTAG, MAX_PROTO, MIN_PORT, MAX_PORT, ACCEPT, DROP, \
    MIN_IPV4, MAX_IPV4, GRE, VXLAN, CTRL_BRIDGE, DATA_BRIDGE, UPLINK_BRIDGE, \
    TUNNEL_BRIDGE, MAX_SUBNET, MAX_TUNNEL_MAC, ANY_IF, WAN_IF, LAN_IF, \
    TCP_PROTO, UDP_PROTO, MAX_WAN_IF_INDEX, VIF_ATTACH, VIF_DETACH, \
    MAX_CONNTRACKS_PER_SEC, MAX_CONNTRACKS

API_VERSION = 'v1'
API_PREFIX = '/' + API_VERSION
DEBUG = False

DATE_PATTEN = '%Y-%m-%d %H:%M:%S'

# HTTP CODE
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500

# OPT_STATUS CODE
SUCCESS = 'SUCCESS'
INVALID_POST_DATA = "INVALID_POST_DATA"
RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'
RESOURCE_ALREADY_EXIST = 'RESOURCE_ALREADY_EXIST'
RESOURCE_UPDATE_ERROR = 'RESOURCE_UPDATE_ERROR'
PARAMETER_ILLEGAL = 'PARAMETER_ILLEGAL'
PREREQUISITES_NOT_SATISFIED = 'PREREQUISITES_NOT_SATISFIED'
SERVER_ERROR = 'SERVER_ERROR'

# File path
LOG_FILE = '/var/log/livegate.log'
ROUTER_SCRIPT = '/usr/local/livegate/script/router.sh'
TUNNEL_SCRIPT = '/usr/local/livegate/script/tunnel.sh'
OVSNAT_SCRIPT = '/usr/local/livegate/script/ovs_nat.sh'
SYSCONF_SCRIPT = '/usr/local/livegate/script/sys_config.sh'
NSP_STAT_SCRIPT = '/usr/local/livegate/script/nsp_stat.sh'

# Constraints
MIN_PROTO = 1
SYSTEM_BOOTUP_WINDOW = 3600
MAX_THREAD = 32
QUEUE_TIME_OUT = 30

# Consts
SNAT = 'SNAT'
DNAT = 'DNAT'
INPUT = 'INPUT'
OUTPUT = 'OUTPUT'
FORWARD = 'FORWARD'
NF_APPEND = 'append'
NF_REPLACE = 'replace'
TUNNEL_FLOW_COOKIE_FORMAT = '0xfff3%06x%06x'

# Callbacks
CALLBACK_TO_LCC_TALKER = 'http://%s:20013/v1/callbacks/'
CALLBACK_SYSTEM_BOOT = 'nsp-bootups/'
CALLBACK_RETRY = 60

FLUSH_LIMIT = 2
MAC_ENTRY_COOKIE = 0x4
MAC_ENTRY_TABLE = 1
PING_SLEEP_TIME = 7
